### ISSUE TITLE
Enhance replication status check

### ISSUE THREAD

**Issue by rauladorean** [layershift/mysql_replication_monitor#8]
Slave_IO_Running checking is not enough.

We had a replication issue where Slave_IO_Running was Yes but Slave_SQL_Running was No
```
MariaDB [(none)]> show slave status\G
*************************** 1. row ***************************
                Slave_IO_State: Waiting for master to send event
                   Master_Host: *.*.*.*
                   Master_User: db_replication
                   Master_Port: 3306
                 Connect_Retry: 60
               Master_Log_File: mariadb-bin.000055
           Read_Master_Log_Pos: 178953897
                Relay_Log_File: relay-bin.000022
                 Relay_Log_Pos: 70706136
         Relay_Master_Log_File: mariadb-bin.000042
              Slave_IO_Running: Yes
             Slave_SQL_Running: No
               Replicate_Do_DB:
           Replicate_Ignore_DB: mysql,performance_schema,information_schema,test
            Replicate_Do_Table:
        Replicate_Ignore_Table:
       Replicate_Wild_Do_Table:
   Replicate_Wild_Ignore_Table:
                    Last_Errno: 1062
                    Last_Error: Could not execute Write_rows_v1 event on table ${db}.${table}; Duplicate entry '288-9044-1' for key 'APACTIONRULE_PRODUCT_RULE_ID_PRODUCT_ID_GROUP_NUMBER', Error_code: 1062; handler error HA_ERR_FOUND_DUPP_KEY; the event's master log mariadb-bin.000042, end_log_pos 85297137
                  Skip_Counter: 0
           Exec_Master_Log_Pos: 85222593
               Relay_Log_Space: 12978938776
               Until_Condition: None
                Until_Log_File:
                 Until_Log_Pos: 0
            Master_SSL_Allowed: No
            Master_SSL_CA_File:
            Master_SSL_CA_Path:
               Master_SSL_Cert:
             Master_SSL_Cipher:
                Master_SSL_Key:
         Seconds_Behind_Master: NULL
 Master_SSL_Verify_Server_Cert: No
                 Last_IO_Errno: 0
                 Last_IO_Error:
                Last_SQL_Errno: 1062
                Last_SQL_Error: Could not execute Write_rows_v1 event on table ${db}.${table}; Duplicate entry '288-9044-1' for key 'APACTIONRULE_PRODUCT_RULE_ID_PRODUCT_ID_GROUP_NUMBER', Error_code: 1062; handler error HA_ERR_FOUND_DUPP_KEY; the event's master log mariadb-bin.000042, end_log_pos 85297137
   Replicate_Ignore_Server_Ids:
              Master_Server_Id: 4
                Master_SSL_Crl:
            Master_SSL_Crlpath:
                    Using_Gtid: No
                   Gtid_IO_Pos:
       Replicate_Do_Domain_Ids:
   Replicate_Ignore_Domain_Ids:
                 Parallel_Mode: optimistic
                     SQL_Delay: 0
           SQL_Remaining_Delay: NULL
       Slave_SQL_Running_State:
              Slave_DDL_Groups: 1633
Slave_Non_Transactional_Groups: 3986
    Slave_Transactional_Groups: 63822
```

We should check:
Slave_IO_Running
Slave_SQL_Running
Seconds_Behind_Master
